steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/demo', '.' ]
  # push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/demo']
  # deploy to cloud run on GKE
- name: "gcr.io/cloud-builders/gcloud"
  args: ['run', 'deploy', 'demo-ui', '--image', 'gcr.io/$PROJECT_ID/demo', '--cluster', 'cloudrun-cluster', '--cluster-location', 'us-central1-c', '--namespace', 'default', '--platform', 'gke']
